### ISSUE TITLE
Object.prototype.toString for pre ES5.1 browers

### ISSUE THREAD

**Issue by pygy** [es-shims/es5-shim#304]
Would you be interested in this?

Pasting from [here](https://github.com/Financial-Times/polyfill-service/pull/401):

----

Object.prototype.toString() is sometimes used as a saner type checker. For example:

```JavaScript
type = {}.toString;

type.call("foo") === "[object String]"
type.call(new String("foo")) === "[object String]"

type.call([]) === "[object Array]"
// etc...
```
It has a lot of advantages over typeof and instanceof for the above types.

In modernish Browsers (ES 5.1) the following also holds:

```JavaScipr
type.call(null) === "[object Null]"
type.call(undefined) === "[object Undefined]"
```

`IE < 9`, `FF < 4` and maybe other browsers however return `'[object Object]'` for these types.

----

Implementation:

```JavaScript

if (Object.prototype.toString.call(null) !== "[object Null]" 
 || Object.prototype.toString.call(undefined) !== "[object Undefined]"
) {
    var Object_prototype_toString = Object.prototype.toString
    Object.prototype.toString = function() {
        if (this === null) return "[object Null]";
        if (this === undefined) return "[object Undefined]";
        return Object_prototype_toString.call(this);
    }
}
```

**Comment by kitcambridge** [comment]
This is a tricky one for two reasons. First, because `this` (pardon the pun :smile_cat:) always defaults to the global scope—`window` in the browser, `global` in Node, `self` in a worker—if set to `null` or `undefined`. So, in ES 3, `{}.toString.call(null) == {}.toString.call(window)`.

This is the default behavior for `call` and `apply` in ES 5, too:

```js
(function(){ return function() { return this; }.call(null) }()) == window;
// => true
(function(){ return function() { return this; }.call(undefined) }()) == window;
// => true
```

Apart from `{}.toString`, the other exception is strict mode:

```js
(function(){ 'use strict'; return function() { return this; }.call(null) }()) === null;
// => true
(function(){ 'use strict'; return function() { return this; }.call(undefined) }()) === undefined;
// => true
```

...But strict mode is ES 5-only, so those semantics can't be replicated in ES 3.

The second consequence of overriding `Object.prototype.toString` is that the `"toString"` property will now be enumerated in every `for...in` loop, since ES 3 doesn't let user code mark properties as non-enumerable. It's possible to work around that with `hasOwnProperty`, but not all code does this, and sometimes, you want to enumerate all inherited properties.

**Comment by ljharb** [comment]
Can you tell me a single JS engine where `Object#toString` behaves differently than this already?

**Comment by pygy** [comment]
I named two in the OP. Most notably ie8-.

**Comment by ljharb** [comment]
ahhh sorry, I misread. interesting idea.

Since comparing to null and undefined are straightforward, and much faster as direct primitive comparisons, I'm going to agree with @kitcambridge's assessment - it's too impractical and doesn't provide enough benefit.

Also note that in ES6, `Object#toString` respects `Symbol.toStringTag`, which means that it is **no longer a reliable branding check** moving forward.

**Comment by michaelficarra** [comment]
Closing because (as @kitcambridge already said above) this is impossible.

**Comment by Xotic750** [comment]
Instead of patching `toString` because of the issues noted, why override `call` instead?
```
Object.prototype.toString.call = function(thisArg) {
    if (thisArg === undefined) {
        return '[object Beep]';
    }
    if (thisArg === undefined) {
        return '[object Boop]';
    }
    return Object.prototype.toString.apply(thisArg);
};
```
I tried this on IE6-8 and it worked fine.

I've been trying to find something that may break by doing it this way but I haven't found anything yet.

One downside that I can think of is if someone copied this `call` onto another function, or used it as a reference instead of `Funtion.prototype.call`, or if they did `call.apply`, but that seems pretty unlikely. 

Also, if you wanted to also patch `Object.prototype.toString.apply`, then you may need to be a bit more creative with something like.

```
Object.prototype.toString.call = function(thisArg) {
    if (thisArg === undefined) {
        return '[object Beep]';
    }
    if (thisArg === undefined) {
        return '[object Boop]';
    }
    return Function.prototype.call(Object.prototype.toString, thisArg);
};
```

Using this method you could also patch other objects that return the incorrect `[[Class]]`. Like the `[[Class]]` of RegExp and some of the TypedArrays.

**Comment by ljharb** [comment]
To be certain it worked, we'd have to patch Function#call and Function#apply. Patching "apply" is very tricky (which is why I still haven't fixed #99) and I suspect patching "call" to be more so.

There's still a cost/benefit decision to be made here, which is, 1) how often do people use `Object#toString` to check for null/undefined at all? 2) Why in an ES6 world would anyone use `Object#toString` ever again, since it's no longer reliable?

I'm all for fixing it, but the more invasive a patch the fix requires, the less worth it it becomes.

**Comment by Xotic750** [comment]
I have started coding up `call` in my fork, and it's looking pretty good so far and yes `apply` will also need to be patched, and hopefully can fix the array/array-like business at the same time. Thing is that there is still lots code out there using `Object#toString` and will continue to be, can't see people not `Object#toString` for some time? I understand the ES6 `Object#toString` argument with the `stringTag` business, but I'm not seeing much support for it yet in browsers (maybe Node?). What is the alternative in ES6, it's not something that I'm aware of? Or maybe there is no ES6 alternative?

**Comment by ljharb** [comment]
There is no ES6 alternative short of using builtin methods that throw, and using try/catch. I have a bunch of "is-something" modules on npm that utilize these techniques as proofs of concept.

**Comment by pygy** [comment]
> Going a bit further, patching `Function.prototype.call` itself.

This is both devious and remarkably astute. I hope you can pull it off in a way that is satisfactory for the project leads.
