### ISSUE TITLE
IE < 8 Error~toString broken

### ISSUE THREAD

**Issue by Xotic750** [es-shims/es5-shim#334]
A test and shim to fix IE < 8 broken Error~toString
```
try {
  throw new Error('test');
} catch (e) {
  if (e.message === 'test' && e.toString() === '[object Error]') {
    Error.prototype.toString = function () {
      var type,
        name,
        msg;
      if (this) {
        type = typeof this;
        if (type !== 'object' && type !== 'function') {
          throw new TypeError();
        }
      }
      name = this.name;
      if (typeof name === 'undefined') {
        name = 'Error';
      } else {
        name = String(name);
      }
      msg = this.message;
      if (typeof msg === 'undefined') {
        msg = '';
      } else {
        msg = String(msg);
      }
      if (!name) {
        return msg;
      }
      if (!msg) {
        return name;
      }
      return name + ': ' + msg;
    };
  }
}
```
http://www.ecma-international.org/ecma-262/5.1/#sec-15.11.4.4

**Comment by ljharb** [comment]
Thanks! (The fix was slightly more complex than this - `String(this.name)` when `this.name` was `typeof` "string" but an exotic object seemed to result in `": "`, so I had to avoid coercing it when `typeof` reported "string" already. Also, `typeof this` shouldn't be "function", it should just be not null/undefined)

**Comment by Xotic750** [comment]
You're welcome, it was some time ago that I looked at this and it was probably never refined. ;)
