### ISSUE TITLE
Object.defineProperty throws exception in IE8

### ISSUE THREAD

**Issue by Nexith** [es-shims/es5-shim#363]
When using Globalize 1.0.0 (https://github.com/jquery/globalize/) and es5-shim version 4.3.1.
es5-shim throws new TypeError(ERR_ACCESSORS_NOT_SUPPORTED);
on line 55 in plural.js from Globalize

The changes in #315 seems to have casued this. If we revert the changes in 0b903e9 it fixes the throw exception in globalize and globalize works fine.

**Comment by ljharb** [comment]
If `globalize` works fine without setting the descriptor, then the problem is in that library - ie, it needs to be aware that the presence of `defineProperty` does not mean you can set getters and setters, and detect it accordingly. I assume you're using the `es5-sham`, the caveats of which are explained in the README?

**Comment by Nexith** [comment]
Yes, you are correct. We where kinda in rush to fix this and I didn't have time the to review if the fault was acually in ```globalize``` or ```es5-shim``` and we thought it fault was in ```es5-shim``` as the ```globalize``` page says ```es5-shim``` will work with getting IE8 support. I will close this issue and open an issue with globalize instead. And yes, we are using the ```es5-sham```.
