### ISSUE TITLE
String#split broken with second argument

### ISSUE THREAD

**Issue by zloirock** [es-shims/es5-shim#380]
[Already 7 month.](https://github.com/es-shims/es5-shim/commit/54666ded0b2307a9e755439542f7ffa0b09ab6f1) [`output` is an array.](https://github.com/es-shims/es5-shim/blob/v4.5.1/es5-shim.js#L1821) Try `typeof 'a b'.split(/ /, 1)`, for example, in IE8.

**Comment by ljharb** [comment]
Thanks! 7 months with no reports likely means nobody's running into it, since using the second arg of split is exceedingly rare.

Fixed and will be released shortly as v4.5.1. I'll also release patches in the 4.1, 4.2, 4.3, and 4.4 lines just in case, since while rare, this could break code that depends on it pretty badly.

**Comment by ljharb** [comment]
all published to npm:

https://github.com/es-shims/es5-shim/releases/tag/v4.1.16
https://github.com/es-shims/es5-shim/releases/tag/v4.2.1
https://github.com/es-shims/es5-shim/releases/tag/v4.3.2
https://github.com/es-shims/es5-shim/releases/tag/v4.4.2
https://github.com/es-shims/es5-shim/releases/tag/v4.5.2
